### ISSUE TITLE
Modificare header single page

### ISSUE THREAD

**Issue by AndreaBarghigiani** [AndreaBarghigiani/wcrm-css#1]
Nella single page c'è da sistemare l'immagine dell'header perché riprende le impostazioni dell'anno scorso mentre noi dovremmo:

- [ ] aumentare l'altezza 
- [ ] mostrare più gatti
- [ ] togliere gradiente

Allego immagine per comprendere meglio:
![schermata 2018-06-25 alle 11 07 13](https://user-images.githubusercontent.com/190159/41841349-58370d52-7868-11e8-86ef-1610974bfed4.jpg)

**Comment by enrico-atzeni** [comment]
fatto, non mi piace molto l'effetto gradino che si ha nel responsive però è un caso limite, non credo ci siano tutte queste persone che vanno a testare come si comporta il sito nel responsive. Comunque fammi sapere come ti sembra, ho cercato di regolare al meglio nei punti critici di width di screen di device comuni e cercando di centrare su tutti i gatti.
Grazie!
