### ISSUE TITLE
Modificare logo inline

### ISSUE THREAD

**Issue by AndreaBarghigiani** [AndreaBarghigiani/wcrm-css#2]
Nel menu il logo presente punta ancora alla vecchia versione, sostituire con il nuovo che si trova a questo indirizzo: `https://2018.rome.wordcamp.org/files/2018/06/wcrm2018-inline-logo.png`

**Comment by enrico-atzeni** [comment]
fatto, ci sarebbe però da aggiungere WordCamp Rome 2018 da qualche parte?

**Comment by AndreaBarghigiani** [comment]
Sì in effetti forse quello è da modificare però direi di farlo vedere a chi ha accesso al sito per avere qualche feedback e probabilmente ho fatto un po' di bordello anche io nella messa in orizzontale del logo. 

Scrivo a chi ha accesso al sito per sapere che ne pensa così poi decidiamo meglio che cosa fare in questi casi.

**Comment by enrico-atzeni** [comment]
immagino questo sia chiuso ora?
Nel caso riaprite pure, grazie!
