### ISSUE TITLE
Invertire colori sezioni home (anche single?)

### ISSUE THREAD

**Issue by AndreaBarghigiani** [AndreaBarghigiani/wcrm-css#3]
In home tutte le immagini di copertina sono bianche e dato che è presente nel tema un effetto parallasse direi di invertire il colore di sfondo in `#333` in modo da dare ritmo alla pagina.

Ecco come potrebbe risultare e occhi agli `::after` e `::before` che danno l'angolazione.

![schermata 2018-06-25 alle 12 01 40](https://user-images.githubusercontent.com/190159/41844216-cd5bb4aa-786f-11e8-8f37-267a718fe04e.jpg)

**Comment by enrico-atzeni** [comment]
@AndreaBarghigiani il button che era già grigio scuro ora diventerebbe invisibile, stavo pensando di metterlo rosso ma si perderebbe la differenza con hover.
Perciò metterei rosso in stato normale e giallo oro in stato :hover, che dici?
![image](https://user-images.githubusercontent.com/19359508/41869598-ce519876-78b9-11e8-89f2-2a185ede8336.png)
![image](https://user-images.githubusercontent.com/19359508/41869632-e1f3ce3a-78b9-11e8-8a8e-4c26cf7e53c1.png)

**Comment by enrico-atzeni** [comment]
P.S. : anche se il testo bianco è molto poco leggibile e lo farei nero, fammi sapere che ne pensi, grazie!
P.P.S. : ho trovato alcune regole già scritte similari dove il testo diventava rosso, spero vada bene, faccio il push così poi mi dici :-)
