### ISSUE TITLE
Aggiungere margine al logo inline su responsive

### ISSUE THREAD

**Issue by AndreaBarghigiani** [AndreaBarghigiani/wcrm-css#5]
Questo è il risultato su mobile, assicurarsi di modificare esclusivamente quando l'effetto del _menu storto_ viene rimosso perché altrimenti il logo non si vede bene.

![screenshot_20180709-193852](https://user-images.githubusercontent.com/190159/42466838-5eac49d8-83b0-11e8-9f3d-20691a920f7b.png)

**Comment by enrico-atzeni** [comment]
fatto!
